# Generated by Django 5.2.16 on 2026-08-03 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.client', verbose_name='cliente/condomínio'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor estimado'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('lead', 'Lead'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('ganha', 'Ganha'), ('perdida', 'Perdida')], default='lead', max_length=20, verbose_name='etapa'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=180, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.client', verbose_name='cliente/condomínio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='gestor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=180, verbose_name='nome do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='progresso (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('em_execucao', 'Em execução'), ('pausado', 'Pausado'), ('concluido', 'Concluído')], default='planejado', max_length=20, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.opportunity', verbose_name='oportunidade'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='rascunho', max_length=20, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='válida até'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='concluída'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='prazo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project', verbose_name='projeto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=180, verbose_name='tarefa'),
        ),
    ]
