# Generated by Django 5.2.16 on 2026-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_opportunity_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='tipo da foto'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='conteúdo da foto'),
        ),
    ]
