# Generated by Django 5.2.16 on 2026-08-03 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_photo_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('manual', 'Cadastro manual'), ('landing_page', 'Landing Page'), ('diario_oficial', 'Diário Oficial')], default='manual', max_length=30, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='rat',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora final'),
        ),
        migrations.AddField(
            model_name='rat',
            name='next_steps',
            field=models.TextField(blank=True, verbose_name='próximos passos'),
        ),
        migrations.AddField(
            model_name='rat',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='rat',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora inicial'),
        ),
        migrations.AddField(
            model_name='rat',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('gerada', 'Gerada'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='rat',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='total de horas'),
        ),
        migrations.AddField(
            model_name='rat',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='versão'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='approved_by_client',
            field=models.BooleanField(default=False, verbose_name='aprovada pelo cliente'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='description',
            field=models.TextField(verbose_name='atividades executadas'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='service_date',
            field=models.DateField(verbose_name='data do atendimento'),
        ),
        migrations.CreateModel(
            name='RATRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.rat')),
            ],
        ),
    ]
