# Generated by Django 5.2.16 on 2026-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_opportunity_source_rat_end_time_rat_next_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora final'),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de execução'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='horas planejadas'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='conclusão (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora inicial'),
        ),
    ]
