# Generated by Django 5.2.17 on 2026-08-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_opportunity_source_rat_end_time_rat_next_steps_and_more'),
        ('core', '0009_task_end_time_task_execution_date_task_planned_hours_and_more'),
        ('core', '0017_reconcile_opportunity_columns'),
    ]

    operations = [
    ]
