# Generated by Django 5.2.17 on 2026-08-13 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260812_0535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('resource_type', models.CharField(choices=[('humano', 'Humano'), ('equipamento', 'Equipamento')], default='humano', max_length=20, verbose_name='tipo')),
                ('detail', models.CharField(blank=True, max_length=180, verbose_name='função / especificação')),
                ('daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='custo diário (R$)')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observações')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rat',
            options={'ordering': ('-service_date',)},
        ),
        migrations.AddField(
            model_name='project',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='término planejado'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='início planejado'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='approved_by_client',
            field=models.BooleanField(default=False, verbose_name='aprovada pelo cliente'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='description',
            field=models.TextField(verbose_name='descrição das atividades'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rats', to='core.project', verbose_name='projeto'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='service_date',
            field=models.DateField(verbose_name='data do atendimento'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='técnico'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(verbose_name='número da medição')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor da medição (R$)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('enviada', 'Enviada ao cliente'), ('paga', 'Paga')], default='aberta', max_length=20, verbose_name='situação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='core.project', verbose_name='projeto')),
            ],
            options={
                'ordering': ('project', 'number'),
            },
        ),
        migrations.AddField(
            model_name='rat',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rats', to='core.measurement', verbose_name='medição'),
        ),
        migrations.AddConstraint(
            model_name='rat',
            constraint=models.UniqueConstraint(fields=('project', 'service_date'), name='uniq_rat_projeto_dia'),
        ),
        migrations.AddField(
            model_name='taskallocation',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.resource', verbose_name='recurso'),
        ),
        migrations.AddField(
            model_name='taskallocation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.task', verbose_name='tarefa'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='uniq_medicao_projeto_numero'),
        ),
    ]
