# Generated by Django 5.2.17 on 2026-08-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_resource_taskallocation_alter_rat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comercial', 'Comercial'), ('tecnico', 'Técnico')], default='tecnico', max_length=12, verbose_name='papel'),
        ),
    ]
