from django.urls import path
from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("autovistoria/", views.autovistoria_landing, name="autovistoria_landing"),
    path("apresentacao/", views.autovistoria_landing, name="presentation"),
    path("primeiro-acesso/", views.first_access, name="first_access"),
    path("meu-cadastro/", views.profile, name="profile"),
    path("", views.dashboard, name="dashboard"),
    path("clientes/", views.clients, name="clients"),
    path("clientes/importar/", views.clients_import, name="clients_import"),
    path("clientes/<int:pk>/consultar-autovistoria/", views.client_autovistoria, name="client_autovistoria"),
    path("clientes/<int:pk>/importar-autovistoria-robo/", views.client_autovistoria_robot_import, name="client_autovistoria_robot_import"),
    path("clientes/<int:pk>/gerar-oportunidade-autovistoria/", views.client_autovistoria_create_opportunity, name="client_autovistoria_create_opportunity"),
    path("clientes/transformar-em-oportunidades/", views.clients_to_opportunities, name="clients_to_opportunities"),
    path("clientes/exportar/<str:fmt>/", views.clients_export, name="clients_export"),
    path("clientes/<int:pk>/contrato/", views.client_contract, name="client_contract"),
    path("<str:resource>/exportar/<str:fmt>/", views.records_export, name="records_export"),
    path("<str:resource>/<int:pk>/excluir/", views.record_delete, name="record_delete"),
    path("oportunidades/", views.opportunities, name="opportunities"),
    path("oportunidades/<int:pk>/carta/", views.opportunity_letter, name="opportunity_letter"),
    path("propostas/", views.proposals, name="proposals"),
    path("projetos/", views.projects, name="projects"),
    path("tarefas/", views.tasks, name="tasks"),
    path("recursos/", views.resources, name="resources"),
    path("alocacoes/", views.allocations, name="allocations"),
    path("rats/", views.rats, name="rats"),
    path("medicoes/", views.measurements, name="measurements"),
    path("projetos/<int:pk>/laudo/", views.project_report, name="project_report"),
    path("diario-oficial/", views.gazette_findings, name="gazette_findings"),
    path("diario-oficial/executar-automatico/", views.gazette_auto_run, name="gazette_auto_run"),
    path("equipe/", views.team, name="team"),
    path("ajuda/", views.help_center, name="help_center"),
]
